-- MySQL Script generated by MySQL Workbench
-- Tue Nov  4 14:42:43 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- USE `mydb` ;

-- -----------------------------------------------------
-- Table `utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utilisateur` (
  `id_utilisateur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `mdp` VARCHAR(255) NOT NULL,
  `role` ENUM('visiteur', 'admin') NOT NULL,
  PRIMARY KEY (`id_utilisateur`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `citation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citation` (
  `id_citation` INT NOT NULL AUTO_INCREMENT,
  `texte` TEXT NOT NULL,
  `auteur` VARCHAR(150) NULL,
  `date_creation` DATETIME NULL,
  `id_utilisateur` INT NOT NULL,
  PRIMARY KEY (`id_citation`),
  INDEX `fk_citation_utilisateur_idx` (`id_utilisateur` ASC) VISIBLE,
  CONSTRAINT `fk_citation_utilisateur`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
